### ISSUE TITLE
Status after initial added a new player is wrong

### ISSUE THREAD

**Issue by rbbuy** [wzolleis/djk-kicker#39]
after initial adding a new player and setting the initial status to 'zugesagt'  it will be turned to 'abgesagt' on the main overview page for the first time -> you have to set the status onesmore

**Comment by wzolleis** [comment]
der Fehler scheint nicht mehr vorhanden zu sein, da die Formulare in der Zwischenzeit umgebaut wurden.

**Comment by wzolleis** [comment]
Fehler tritt nicht mehr auf
