### ISSUE TITLE
adding new player with spaces before/after name and a mailaddress like mymail_at_mail.mail (invalid mailaddress)

### ISSUE THREAD

**Issue by rbbuy** [wzolleis/djk-kicker#40]
... after Save happens:
![Unbenannt](https://user-images.githubusercontent.com/79504176/204766584-1ac01279-f1fd-4926-a30b-d494a92e7649.png)

**Comment by rbbuy** [comment]
it may also be necessary to trim the mail address

**Comment by wzolleis** [comment]
Mailadresse muss jetzt ein "@" enthalten. Leerzeichen vor u. hinter dem Wert werden entfernt. (trim)
