### ISSUE TITLE
re-use an URL on an other browser cause authentication warning

### ISSUE THREAD

**Issue by rbbuy** [wzolleis/djk-kicker#42]
using an url (working on a first used browser) on an other browser an authentication warning occurs.
Nevertheless it's possible to use the 'Player hinzufügen' button

example url: https://djk-kicker.netlify.app/application/games/clb1djxru0001ld08x3fnnxth

**Comment by wzolleis** [comment]
Der Beispiellink enthält kein Token, deshalb ist es ok, dass der Hinweis im zweiten Browser kommt. 
Die URL funktioniert auf dem ersten Browser, da vermutlich in diesem Browser die Seite früher mit einem Token geöffnet  wurde.  Das Token wird in einem Session-Cookie gespeichert. Das Cookie ist aktuell 7 Tage (also bis zum nächsten Spieltag) gültig. Solange das Cookie aktiv ist, wird kein Hinweistext mehr angezeigt. 

Als Bugfix wird noch folgende Änderung gemacht:
* Der Button ist nicht mehr sichtbar, wenn das Token fehlt bzw. kein Cookie vorhanden ist.
