### ISSUE TITLE
GUI: using other then default fonts

### ISSUE THREAD

**Issue by rbbuy** [wzolleis/djk-kicker#44]
using other then default fonts cause different rendering on different browsers: 
 
![image](https://user-images.githubusercontent.com/79504176/204820560-5d116496-0746-403a-a465-6ba3a1dc73ef.png)

sometimes it will be used a different substitude font, or a mixture of several fonts, may be depending on fontsize

**Comment by TimZolleis** [comment]
Screenshot should be referring to an old version, that type of drop-down should not exist anymore.

Will definitely look into it.
